### ISSUE TITLE
pip3 not found

### ISSUE THREAD

**Issue by jennettageorge** [ThoughtWorksInc/CD4ML-Scenarios#3]
Im working through your instructions and I get the following error in my Jenkins pipeline build:

`/var/jenkins_home/workspace/CD4ML-Scenarios_master@tmp/durable-01e5a6c2/script.sh: line 1: pip3: not found
script returned exit code 127`

![image](https://user-images.githubusercontent.com/41783948/84511433-81245280-ac94-11ea-88c5-03548337535f.png)

I've tried changing pip3 to pip, but I get the same error with `pip: not found`.

**Comment by ericnagler** [comment]
Another user reported a similar problem to this one. Just making sure, are you using the Jenkins that is provided as part of the Docker Container? You can find this at http://localhost:10000/blue. One thing you can try is to reset your Docker containers and pull again. Be aware, the first two commands will clear all of your containers and volumes on your machine.

```
docker system prune --all
docker system prune --volumes
docker-compose up -d --build --remove-orphans
```

**Comment by jennettageorge** [comment]
Thanks @ericnagler that was my exact problem, I was using an incorrect docker file. I am not experiencing another issue with MLFlow container not working but it seems to be unrelated to this, so this issue can be closed.

**Comment by ericnagler** [comment]
No problem @jennettageorge . If you have any further problems, just reply back! Thanks!
